### PR TITLE
version 1.4.0 changes

### PR DESCRIPTION
**Pull request by sildater**
updated notebooks to work with version 1.4.0 of partitura

specific changes
---------------

- performance_codec refactor
- fastdtw bug with numpy matrices instead of arrays
- point to current version of (n)ASAP, discard match file generation
- minor local only bugs in lightning model: num_workers to default, casting to LongTensor

### CODE REVIEW

**Comment by manoskary** [comment]
This PR looks good to me, it works with the last version of partitura. I didn't notice any notebook compilation errors or paths. Two minor commits were added to adress the numbering issue of the notebooks and a minor dependency addition potentially for better html compilation.

**Review by manoskary — APPROVED** [review]
